name: Auto Sync Fork

on:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨3点自动运行
  workflow_dispatch:      # 支持手动触发

permissions:
  contents: write         # ✅ 允许 push 到仓库

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and sync
        run: |
          # ✅ 你的上游仓库
          git remote add upstream https://github.com/ourongxing/newsnow.git

          # 拉取上游更新
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Auto sync from upstream"

      - name: Push changes to your fork
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git main
