name: Auto Sync Fork

on:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨3点自动同步（UTC时间）
  workflow_dispatch:      # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and sync
        run: |
          # 替换成原始仓库地址 ↓
          git remote add upstream https://github.com/ourongxing/newsnow

          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Auto sync from upstream"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
